/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 4e640f9cc24f9bb457a15fdbacce1dd0)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_BASE_URL: "https://twstock.xiehnet.com";
	CLOUDFLARE_WORKERS: "true";
	WORKER_SELF_REFERENCE: Fetcher /* tw-stock-tracker */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_BASE_URL" | "CLOUDFLARE_WORKERS">> {}
}
